development:
  adapter: postgresql
  encoding: unicode
  database: modern_idx_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: modern_idx_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: modern_idx_production
  host: localhost
